sudo: required

language: generic

env:
  - BROWSER=chrome
  - BROWSER=firefox

services:
  - docker

before_script:
  - cd tests
  - docker-compose run --rm node npm run build
  - docker-compose up -d

script:
  - docker-compose ps
  # exclude optional tests
  - docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$BROWSER --grep '(?=.*)^(?!.*@optional)'