name: Build and Test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - selenium-browser: "chrome"
          - selenium-browser: "firefox"
      fail-fast: false

    env:
      SELENIUM_BROWSER: ${{ matrix.selenium-browser }}
      BUILD_ENV: "build.prod"

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
          npm install
      - name: Test
        run: |
          cd tests
          docker-compose up -d node $SELENIUM_BROWSER
          docker-compose exec node npm run $BUILD_ENV
