name: Build and Test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - selenium-browser: "chrome"
            optional-tests: [false, true]
          - selenium-browser: "firefox"
            optional-tests: [false, true]
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: tests

    env:
      SELENIUM_BROWSER: ${{ matrix.selenium-browser }}
      BUILD_ENV: "build.prod"

    steps:
      - uses: actions/checkout@v1
      #- name: Install
      #  run: |
      #    npm install
      - name: Install
        run: docker-compose run -T --rm node npm install
      - name: Start
        run: docker-compose up -d ${SELENIUM_BROWSER}
      - name: Build
        run: docker-compose run -T --rm node npm run ${BUILD_ENV}
      - name: Test
        if: ${{ !matrix.optional-tests }}
        run: docker-compose exec -T node codeceptjs -c /repo/tests/codeceptjs/codecept.json run-multiple basic:${SELENIUM_BROWSER} --invert --grep  '@optional'
      - name: Test (optional)
        if: ${{ matrix.optional-tests }}
        run: docker-compose exec node codeceptjs -c /repo/tests/codeceptjs/codecept.json run-multiple basic:$SELENIUM_BROWSER --grep '@optional'


