name: Build and Test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - selenium-browser: "chrome"
          - selenium-browser: "firefox"
      fail-fast: false

    env:
      SELENIUM_BROWSER: ${{ matrix.selenium-browser }}
      BUILD_ENV: "build.prod"

    steps:
      - uses: actions/checkout@v1
      #- name: Install
      #  run: |
      #    npm install
      - name: Init
        run: |
          cd tests
          docker-compose up -d node ${SELENIUM_BROWSER}
      - name: Install
        run: docker-compose run -T --rm node npm install
      - name: Build
        run: docker-compose exec -T node npm run ${BUILD_ENV}
      - name: Test
        run: docker-compose exec -T node codeceptjs -c /repo/tests/codeceptjs/codecept.json run-multiple basic:${SELENIUM_BROWSER} --invert --grep  '@optional'


